==== OGC API - Environmental Data Retrieval

An Environmental Data Retrieval (EDR) API footnote:[https://ogcapi.ogc.org/edr] provides a family of lightweight interfaces to access Environmental Data resources. Each resource addressed by an EDR API maps to a defined query pattern. This specification identifies resources, captures compliance classes, and specifies requirements which are applicable to OGC Environmental Data Retrieval API’s. This specification addresses two fundamental operations; discovery and query. Discovery operations allow the API to be interrogated to determine its capabilities and retrieve information (metadata) about this distribution of a resource. This includes the API definition of the server as well as metadata about the Environmental Data resources provided by the server. Query operations allow Environmental Data resources to be retrieved from the underlying data store based upon simple selection criteria, defined by this standard and selected by the client.

The OGC API - Environmental Data Retrieval Standard provides a family of lightweight query interfaces to access spatio-temporal data resources by requesting data at a Position, within an Area, along a Trajectory or through a Corridor.

The OGC API - Environmental Data Retrieval - Part 2: Publish-Subscribe Workflow Standard provides recommendations on applying Publish-Subscribe (PubSub) architectural patterns to implementations of one or more OGC API Standards in order to support Event Driven applications.

