name: Test WMO Met Data Exchange Interoperability Experiment

on:
  pull_request:
    paths:
      - '**.adoc'   
      
env:
  FILE_BASENAME: metdx-ie-DRAFT

jobs:
  build-metdx-ie:
    name: Test documentation build
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update -y \
          && sudo apt-get install -y pandoc \
          && sudo gem install asciidoctor asciidoctor-pdf
      - name: checkout repository
        uses: actions/checkout@master
      - name: build documentation
        run: |
          cd metdx-ie \
          && asciidoctor --trace -o /tmp/metdx-ie/metdx-ie/${FILE_BASENAME}.html index.adoc \
          && asciidoctor -a allow-uri-read --trace --backend docbook --out-file - index.adoc | pandoc --from docbook --to docx --output /tmp/metdx-ie/metdx-ie/${FILE_BASENAME}.docx \
          && asciidoctor -a allow-uri-read --trace -r asciidoctor-pdf --trace -b pdf -o /tmp/metdx-ie/metdx-ie/${FILE_BASENAME}.pdf index.adoc
